services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/koda-db
    volumes:
      - ./backend/public:/usr/src/app/public
      - ./backend/src:/usr/src/app/src
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: koda-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
