version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "4000:4000"
      - "2221:22"
    networks:
      - my-network
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/koda-db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - my-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
