version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "4000:4000"
      - "2221:22"
    networks:
      - my-network
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/koda-db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: koda-db
    ports:
      - "5432"
    networks:
      - my-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge
volumes:
  pgdata:
